INSERT INTO `shoes` (`id`, `name`, `brand`, `category`, `type`, `size`, `price`, `color`, `description`, `image`, `created_at`, `updated_at`, `stock`) VALUES
(1, 'Breaknet Sleek', 'Adidas', 'Sportowe', 'Dla kobiet', '["38", "39", "40", "41", "42"]', 239.99, 'Niebieski', 'Przedstawiamy stylowe buty Breaknet Sleek. Zainspirowane ponadczasową elegancją klasycznych butów sportowych dodają wyrafinowanego charakteru codziennym stylizacjom. Niezależnie od tego, czy zwiedzasz ulice miasta, czy spędzasz dzień na świeżym powietrzu, są idealnym wyborem, jeśli zależy Ci na swobodnym stylu.', 'zdj/BreaknetSleek_01.jpg', '2026-04-26 13:16:32', '2026-04-26 13:16:32', 0),
(2, 'Carina 2.0', 'Puma', 'Sportowe', 'Dla kobiet', '["38", "39", "40", "41", "42"]', 209.99, 'Biały', 'Te stylowe buty to połączenie najwyższej jakości skóry i skóry syntetycznej, które zostały wykonane z materiałów pochodzących z recyklingu. Ich podeszwa środkowa i zewnętrzna z gumy zapewniają doskonałą trwałość i przyczepność. Dodatkowo, wkładka SoftFoam+ gwarantuje nie tylko doskonałą amortyzację, ale także optymalny komfort na każdym kroku. To buty, które łączą styl, jakość wykonania i troskę o środowisko naturalne.', 'zdj/Carina2.0_01.jpg', '2026-04-26 13:29:28', '2026-04-26 13:29:28', 5),
(3, 'CHARGE', 'Rebook', 'Sportowe', 'Dla kobiet', '["38", "39", "40", "41", "42"]', 279.99, 'Beżowy jasny', 'Stylowe damskie sneakersy marki Reebok to połączenie modnego designu z niezrównanym komfortem. Wykonane z wysokiej jakości skóry naturalnej zamszowej i materiału włókienniczego, oferują trwałość i wyjątkowy wygląd. Gruba podeszwa zapewnia doskonałą amortyzację, a klasyczne sznurowanie umożliwia idealne dopasowanie do stopy. Dzięki zastosowanym technologiom Ortholite i Comfort Footbed, każdy krok staje się niezwykle wygodny i przyjemny. Okrągły nosek dodaje uniwersalności, a sportowy styl sprawia, że buty będą świetnym uzupełnieniem codziennych, miejskich stylizacji. Postaw na komfort w sportowym wydaniu!', 'zdj/Charge_01.jpg', '2026-04-26 13:41:14', '2026-04-26 13:41:14', 5),
(4, 'Czółenka', 'Gino Rossi', 'Eleganckie', 'Dla kobiet', '["38", "39", "40", "41", "42"]', 299.99, 'Czarny', 'Dodaj swojej stylizacji nutę elegancji z damskimi czółenkami Gino Rossi. Wykonane z wysokiej jakości skóry naturalnej, te buty łączą w sobie klasę i wyrafinowanie, które doskonale dopełnią każdą wizytową kreację. Smukła szpilka dodaje sylwetce lekkości i podkreśla jej kobiecą zmysłowość, a szpiczasty nosek nadaje całości subtelności i szyku. Idealne na wyjątkowe okazje i wieczorowe wyjścia, czółenka Gino Rossi to nie tylko oznaka dobrego gustu, ale także gwarancja wygody dzięki starannemu wykonaniu i najwyższej jakości materiałom. Wybierz klasykę w nowoczesnym wydaniu i poczuj się pewnie przy każdym kroku!', 'zdj/Czolenka_01.jpg', '2026-04-26 13:45:06', '2026-04-26 13:45:06', 5),
(5, 'Day One', 'Converse', 'Sportowe', 'Dla mężczyzn', '["38", "39", "40", "41", "42"]', 219.99, 'Czarny', 'Męskie tenisówki Converse to prawdziwa klasyka w sportowym wydaniu. Wykonane z wysokiej jakości materiału włókienniczego, są lekkie, przewiewne i zapewniają komfort przez cały dzień. To idealny wybór na co dzień – zarówno do casualowych, jak i bardziej streetwearowych stylizacji. Ich minimalistyczny, a zarazem ponadczasowy design doskonale wpisuje się w każdą garderobę, dodając jej miejskiego charakteru. Szukasz wygody, która idzie w parze z kultowym stylem? Te tenisówki są stworzone właśnie dla Ciebie! Idealne na spacer po mieście, spotkanie z przyjaciółmi czy weekendowy wypad za miasto – niezawodność i styl w jednym. Postaw na klasyczną jakość i poczuj się świetnie w każdej sytuacji.', 'zdj/DayOne_01.jpg', '2026-04-26 13:49:43', '2026-04-26 13:49:43', 5),
(6, 'Enzo 2', 'Puma', 'Sportowe', 'Dla mężczyzn', '["38", "39", "40", "41", "42"]', 299.99, 'Czarny', 'Wybierz męskie buty sportowe Puma i ciesz się komfortem na najwyższym poziomie. Wykonane z włókienniczego materiału, zapewniają odpowiednią przewiewność i lekkość. Płaska, elastyczna podeszwa gwarantuje stabilność, a zastosowane technologie SoftFoam i EVA dbają o wyjątkową wygodę i amortyzację. Pianka SoftFoam skutecznie redukuje nacisk na stopy, zwiększając komfort podczas długiego noszenia, natomiast podeszwa EVA zapewnia lekkość i sprężystość każdego kroku. Postaw na niezawodność i styl marki Puma!', 'zdj/Enzo_01.jpg', '2026-04-26 13:53:21', '2026-04-26 13:53:21', 5),
(7, 'Milton', 'Vans', 'Sportowe', 'Dla mężczyzn', '["38", "39", "40", "41", "42"]', 239.99, 'Czarny', 'Dodaj do swojej kolekcji niezawodne męskie tenisówki od kultowej marki Vans! Wykonane ze skóry, łączą trwałość z ponadczasowym stylem, dzięki któremu doskonale sprawdzą się zarówno na co dzień, jak i w bardziej casualowych stylizacjach. To idealne połączenie wygody i modnego designu, które odpowiada wymaganiom nowoczesnych mężczyzn. Postaw na Vans i ciesz się komfortem każdego kroku!', 'zdj/Milton_01.jpg', '2026-04-26 13:55:33', '2026-04-26 13:55:33', 5),
(8, 'Nebzed Basic', 'Adidas', 'Sportowe', 'Dla mężczyzn', '["38", "39", "40", "41", "42"]', 239.99, 'Biały', 'Buty do biegania adidas to idealny wybór dla mężczyzn, którzy czerpią radość z aktywności fizycznej. Wykonane z wytrzymałego i lekkiego materiału tekstylnego, zapewniają optymalny komfort i wsparcie przy każdym kroku. Ich sportowy charakter sprawia, że świetnie sprawdzą się zarówno podczas intensywnych treningów, jak i rekreacyjnych biegów. Precyzyjne dopasowanie oraz oddychalność materiału przyczyniają się do maksymalnej wygody, dzięki czemu możesz w pełni skupić się na swoich celach. Postaw na jakość, która dotrzyma Ci kroku na każdej trasie!', 'zdj/NebzedBasic_01.jpg', '2026-04-26 13:57:17', '2026-06-01 16:36:49', 2),
(9, 'Półbuty skórzane', 'Gino Rossi', 'Eleganckie', 'Dla mężczyzn', '["38", "39", "40", "41", "42"]', 299.99, 'Czarny', 'Szukasz elegancji w klasycznym wydaniu? Męskie półbuty marki Gino Rossi to kwintesencja stylu i ponadczasowego szyku. Wykonane z wysokiej jakości skóry naturalnej, prezentują się wyjątkowo elegancko, a jednocześnie zapewniają trwałość i komfort noszenia. Ich okrągły nosek nadaje subtelną, uniwersalną formę, która doskonale wpisze się w wizytowe stylizacje. Te półbuty to idealny wybór na specjalne okazje, ale także na co dzień, kiedy chcesz dodać swojemu wyglądowi klasy. Postaw na niezawodną jakość i ponadczasowy design – Twoje stopy zasługują na to, co najlepsze!', 'zdj/Polbuty_01.jpg', '2026-04-26 14:00:05', '2026-04-26 14:00:05', 5),
(10, 'Rickie Classic V PS', 'Puma', 'Sportowe', 'Dla dzieci', '["28", "29", "30", "31", "32"]', 139.99, 'Różowy', 'Szukasz idealnych butów sportowych dla Twojego dziecka? Postaw na różowe buty sportowe marki Puma! Wykonane z wysokogatunkowego tworzywa syntetycznego, te buty zapewniają trwałość i wygodę podczas każdej aktywności. Dzięki zapięciu na rzep, zakładanie i zdejmowanie jest szybkie i łatwe, co sprawia, że są idealne dla małych, aktywnych użytkowników. Okrągły nosek zapewnia dodatkowy komfort i ochronę dla małych stóp. Te stylowe i funkcjonalne buty sportowe to doskonały wybór na codzienne przygody i sportowe wyzwania. Wybierz jakość i styl z marką Puma!', 'zdj/Rickie_01.jpg', '2026-04-26 14:09:22', '2026-04-26 14:09:22', 5),
(11, 'Run 70s 2.0', 'Adidas', 'Sportowe', 'Dla kobiet', '["38", "39", "40", "41", "42"]', 299.99, 'Beżowy', 'Wzbogać swoją garderobę o stylowe damskie sneakersy adidas, które łączą w sobie modny design i funkcjonalność. Wykonane z zamszu i materiału tekstylnego, zapewniają trwałość i przewiewność, dzięki czemu Twoje stopy pozostaną świeże przez cały dzień. Te sneakersy to idealny wybór dla kobiet, które cenią sobie połączenie sportowego stylu z oryginalną estetyką. Doskonale sprawdzą się zarówno w casualowych, jak i bardziej wyrafinowanych stylizacjach. Wybierz obuwie, które podkreśli Twój unikalny gust i zapewni wygodę każdego kroku!', 'zdj/Run70s2.0_01.jpg', '2026-04-26 14:14:03', '2026-04-26 14:14:03', 5),
(12, 'VL Move EL C', 'Adidas', 'Sportowe', 'Dla dzieci', '["28", "29", "30", "31", "32"]', 129.99, 'Czarny', 'Te chłopięce sneakersy adidas to połączenie wygody, stylu i nowoczesnych technologii. Wykonane z trwałego materiału włókienniczego i wysokogatunkowego tworzywa syntetycznego, gwarantują lekkość i oddychalność przez cały dzień. Okrągły nosek zapewnia komfort noszenia, a praktyczne zapięcie na rzep w połączeniu z elastycznymi sznurówkami ułatwia szybkie zakładanie i zdejmowanie. Dzięki technologii Cloudfoam, buty oferują lekką amortyzację, doskonałą miękkość i komfort przy każdym kroku – idealne na aktywne dni w szkole czy podczas spacerów.', 'zdj/VLMOVE_01.jpg', '2026-04-26 14:17:07', '2026-04-26 14:17:07', 5),
(13, 'VS Switch 3', 'Adidas', 'Sportowe', 'Dla dzieci', '["28", "29", "30", "31", "32"]', 129.99, 'Niebieski', 'Szukasz stylowych i wygodnych butów dla swojego dziecka? Postaw na sportowe sneakersy marki adidas! Wykonane z wysokogatunkowego tworzywa syntetycznego, gwarantują trwałość i komfort noszenia każdego dnia. Okrągły nosek zapewnia wygodę, a zapięcie na rzep ułatwia szybkie zakładanie i zdejmowanie butów, co docenią zarówno dzieci, jak i ich rodzice. Sportowy styl tych sneakersów sprawia, że świetnie sprawdzą się zarówno podczas aktywności fizycznej, jak i w codziennych stylizacjach. Idealny wybór na każdy dzień pełen zabawy i ruchu!', 'zdj/VsSwitch_01.jpg', '2026-04-26 14:19:13', '2026-04-26 14:19:13', 0);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `shoes`
--
ALTER TABLE `shoes`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `shoes`
--
ALTER TABLE `shoes`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
